Repository prgrms-fe-devcourse/FEDC4_TMI_HOMERS_OFF, pull requests merged in 2023-09, with the labels that each got.

#2 Init/setting
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.tsx
  src/api/index.ts
  src/assets/index.ts
  src/components/index.ts
  src/context/index.ts
  src/hooks/index.ts
  src/index.css
  src/main.tsx
  src/pages/index.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/button.css
  src/types/index.ts
  src/utils/index.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: Chore, FE

#8 Feat: RouterProvider, QueryProvider, AxiosInstance 생성, react-icons 설치, 라우팅 설정
  .commitlintrc.json
  .gitignore
  .husky/commit-msg
  package-lock.json
  package.json
  src/App.tsx
  src/api/axiosClient.ts
  src/main.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticlesPage.tsx
  src/pages/HomePage.tsx
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/NewArticlePage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/pages/SignupPage.tsx
  src/pages/index.ts
  src/utils/Router.tsx
Labels: 🏅 Chore, 🐣 Feat

#12 design : Input, Errortext 컴포넌트 생성 및 추가 작업
  .storybook/preview.ts
  package-lock.json
  package.json
  src/components/ErrorText.tsx
  src/components/Input.tsx
  src/index.css
  src/pages/SignupPage.tsx
  src/stories/Button.tsx
  src/stories/ErrorText.stories.tsx
  src/stories/Input.stories.tsx
  tailwind.config.js
Labels: 🏅 Chore, 🐣 Feat

#14 fix: vercel.json 추가
  vercel.json
Labels: 🔨 Fix, ✏️ Study

#22 feat: 회원가입 구현
  src/App.tsx
  src/pages/SignupPage.tsx
Labels: ✏️ Study

#20 feat : 회원가입 기능
  src/App.tsx
  src/api/auth.ts
  src/api/axiosClient.ts
  src/api/signUp.ts
  src/components/Loader.tsx
  src/context/AuthContext.tsx
  src/hooks/useAuthContext.tsx
  src/hooks/useSignUp.tsx
  src/pages/SignupPage.tsx
  src/types/Channel.ts
  src/types/Comment.ts
  src/types/Conversation.ts
  src/types/Follow.ts
  src/types/Like.ts
  src/types/Message.ts
  src/types/Notification.ts
  src/types/Post.ts
  src/types/User.ts
  src/types/signUp.ts
  src/utils/Router.tsx
  src/utils/localStorage.ts
Labels: 🐣 Feat

#30 hotFix: types 폴더 type으로 변경
  src/api/auth.ts
  src/api/signUp.ts
  src/context/AuthContext.tsx
  src/type/Channel.ts
  src/type/Comment.ts
  src/type/Conversation.ts
  src/type/Follow.ts
  src/type/Like.ts
  src/type/Message.ts
  src/type/Notification.ts
  src/type/Post.ts
  src/type/User.ts
  src/type/index.ts
  src/type/signUp.ts
  src/utils/Router.tsx
  tsconfig.json
  vite.config.ts
Labels: 🔨 Fix

#29 chore: react-error-boundary 설치
  package-lock.json
  package.json
Labels: 🏅 Chore

#19 feat: MainButton 공통 컴포넌트 추가
  src/components/MainButton.tsx
  src/stories/MainButton.stories.tsx
Labels: 🐣 Feat

#34 study: 회원가입 기능 스터디
  .commitlintrc.json
  .config/cz-config.js
  .husky/pre-push
  .storybook/preview.ts
  package-lock.json
  package.json
  src/components/ErrorText.tsx
  src/components/Input.tsx
  src/index.css
  src/pages/SignupPage.tsx
  src/stories/Button.tsx
  src/stories/ErrorText.stories.tsx
  src/stories/Input.stories.tsx
  tailwind.config.js
  vercel.json
Labels: ✏️ Study

#21 design: Article, Avatar 공통 컴포넌트 추가
  src/components/Article.tsx
  src/components/Avatar.tsx
  src/stories/Article.stories.tsx
  src/stories/Avatar.stories.tsx
  tailwind.config.js
Labels: 🎨 Design

#27 feat: 회원가입 페이지 추가
  src/pages/SignupPage.tsx
Labels: ✏️ Study

#38 refactor: modeClasses 함수에서 객체로 변경
  src/components/MainButton.tsx
Labels: 🛠 Refactor

#25 feat: CloseButton, BackButton 컴포넌트 구현
  src/components/BackButton.tsx
  src/components/CloseButton.tsx
  src/stories/BackButton.stories.tsx
  src/stories/CloseButton.stories.tsx
Labels: 🐣 Feat

#40 feat: 회원가입 페이지 추가
  src/pages/SignupPage.tsx
Labels: ✏️ Study

#41 design: formInput 컴포넌트
  src/App.tsx
  src/components/ErrorText.tsx
  src/components/FormInput.tsx
  src/components/Input.tsx
  src/pages/SignupPage.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Input.stories.tsx
  src/stories/button.css
  tailwind.config.js
Labels: 🎨 Design

#43 design: article-info-icon 공통 컴포넌트 구현
  src/components/ArticleInfoIcon.tsx
  src/stories/ArticleInfoIcon.stories.tsx
Labels: 🎨 Design

#50 design: Notice 컴포넌트
  src/components/Notice.tsx
  src/stories/Notice.stories.tsx
  tailwind.config.js
Labels: 🎨 Design

#49 design: subButton 컴포넌트 추가
  src/components/SubButton.tsx
  src/stories/SubButton.stories.tsx
  tailwind.config.js
Labels: 🎨 Design

#58 fix: HeaderText 공통 컴포넌트 props 타입 수정
  src/components/HeaderText.tsx
Labels: 🔨 Fix

#45 design: Subscribe, Tab, TabItem 공통 컴포넌트 추가
  src/components/SubscribeInfo.tsx
  src/components/Tab.tsx
  src/components/TabItem.tsx
  src/constants/Tab.ts
  src/stories/SubscribeInfo.stories.tsx
  src/stories/Tab.stories.tsx
  src/utils/getKeyByValue.ts
Labels: 🎨 Design

#51 design: Comment 공통 컴포넌트 추가
  src/components/BackButton.tsx
  src/components/CloseButton.tsx
  src/components/Comment.tsx
  src/stories/Comment.stories.tsx
Labels: 🎨 Design

#63 refactor: Tab, Article 공통 컴포넌트 수정
  src/components/Article.tsx
  src/components/Tab.tsx
  src/stories/Tab.stories.tsx
  src/utils/getTimeDelta.ts
Labels: 🛠 Refactor, 🔥 우선순위 높음

#64 Fix: 로컬 폰트 방식으로 변경
  public/fonts/Cafe24Ssurround-v2.0.woff2
  public/fonts/Cafe24SsurroundAir-v1.1.woff2
  src/index.css
  tailwind.config.js
Labels: 🔨 Fix

#67 design: logo svg 파일 추가
  public/img/logo.svg
Labels: 🎨 Design

#70 fix: auth에 json parsing 추가
  src/api/auth.ts
Labels: 🔨 Fix

#53 feat: 검색페이지 스터디 with debounce
  src/pages/SearchPage.tsx
Labels: ✏️ Study

#59 feat: 검색 기능 구현
  src/api/search.ts
  src/hooks/useDebounce.tsx
  src/pages/SearchPage.tsx
  src/types/Comment.ts
  src/types/Like.ts
  src/types/Message.ts
  src/types/Post.ts
  src/types/User.ts
Labels: ✏️ Study

#72 feat: 글작성 페이지 구현
  src/pages/NewArticlePage.tsx
  src/pages/SignupPage.tsx
  src/types/Like.ts
  src/types/Message.ts
  src/types/Post.ts
  src/types/User.ts
  src/types/signUp.ts
Labels: ✏️ Study

#71 feat: 글 작성 페이지 스터디
  src/hooks/useSearch.tsx
  src/pages/NewArticlePage.tsx
Labels: ✏️ Study

#73 feat: 게시판 페이지 레이아웃 구현 (초안)
  src/components/Article.tsx
  src/constants/Article.ts
  src/hooks/useArticles.tsx
  src/hooks/useFilteredArticles.tsx
  src/pages/ArticlesPage.tsx
  src/stories/Tab.stories.tsx
Labels: 🐣 Feat

#87 Feat: 비밀번호 보여주는 토글버튼 추가
  src/api/auth.ts
  src/components/FormInput.tsx
  src/context/AuthContext.tsx
  src/hooks/useSignUp.tsx
  src/pages/SignupPage.tsx
Labels: 🐣 Feat, 🔨 Fix

#83 fix: article 공통 컴포넌트 storybook 오류 수정
  src/stories/Article.stories.tsx
Labels: 🔨 Fix

#92 feat: 로그인하기
  src/api/login.ts
  src/hooks/useLogin.tsx
  src/pages/LoginPage.tsx
Labels: 🐣 Feat

#95 feat: NotFoundPage구현
  public/img/404.png
  src/pages/NotFoundPage.tsx
Labels: 🐣 Feat

#90 refactor: Tab, TabItem, ArticlesPage 리팩토링
  src/components/Tab.tsx
  src/components/TabItem.tsx
  src/context/TabContext.tsx
  src/hooks/useTabContext.tsx
  src/pages/ArticlesPage.tsx
  src/stories/Tab.stories.tsx
Labels: 🛠 Refactor

#99 refactor: subButton 컴포넌트 코드 수정
  src/components/SubButton.tsx
  src/stories/SubButton.stories.tsx
Labels: 🛠 Refactor

#97 feat: ProfilePage 컴포넌트 레이아웃 추가
  src/components/Article.tsx
  src/components/Avatar.tsx
  src/components/BottomNavigation.tsx
  src/components/SubscribeInfo.tsx
  src/components/TabItem.tsx
  src/pages/ProfilePage.tsx
Labels: 🐣 Feat

#107 fix: BottomNavigation 컴포넌트 storybook error 해결
  src/components/BottomNavigation.tsx
  src/stories/BottomNavigation.stories.tsx
Labels: 🔨 Fix

#101 design : 알림 페이지 레이아웃
  src/components/Notice.tsx
  src/main.tsx
  src/pages/LandingPage.tsx
  src/pages/NotificationPage.tsx
Labels: 🐣 Feat, 🎨 Design, 🔥 우선순위 높음

#105 design: 글 작성 페이지 레이아웃
  src/api/saveArticle.ts
  src/components/TabItem.tsx
  src/constants/NewArticle.ts
  src/hooks/useArticle.tsx
  src/pages/NewArticlePage.tsx
Labels: 🎨 Design

#109 feat: ArticlesPage 컴포넌트 구현
  src/hooks/useArticles.tsx
  src/hooks/useFilteredArticles.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/Articles.tsx
  src/pages/ProfilePage.tsx
Labels: 🐣 Feat

#114 fix: TabItem type 선언 오류 해결
  src/components/TabItem.tsx
Labels: 🔨 Fix

#110 design: 프로필 수정 페이지 레이아웃
  src/pages/ProfileEditPage.tsx
  src/pages/ProfileEditPage/EditForm.tsx
  src/pages/index.ts
  src/utils/Router.tsx
Labels: 🐣 Feat, 🎨 Design, 🔥 우선순위 높음

#112 feat: 랜딩 페이지 화면 및 버튼 구현
  public/img/character.png
  src/pages/LandingPage.tsx
  src/pages/temp.tsx
  tailwind.config.js
Labels: 🐣 Feat

#115 design: Toast 공통 컴포넌트 구현
  src/components/Toast.tsx
  src/stories/Toast.stories.tsx
  tailwind.config.js
Labels: 🎨 Design

#116 fix: 아티클 폰트 사이즈 수정
  src/components/Article.tsx
  src/index.css
  tailwind.config.js
Labels: 🔨 Fix

#117 fix: 캐치프레이즈 줄바꿈 수정
  src/pages/LandingPage.tsx
Labels: 🔨 Fix, 🔥 우선순위 높음

#118 feat: 임시 navbar 추가
  src/App.tsx
Labels: 🐣 Feat, 💧 우선순위 낮음

#119 Feat : api 함수 추가
  src/api/auth.ts
  src/api/axiosClient.ts
  src/api/common/Auth.ts
  src/api/common/Comment.ts
  src/api/common/Follow.ts
  src/api/common/Like.ts
  src/api/common/Notification.ts
  src/api/common/Post.ts
  src/api/common/Search.ts
  src/api/common/User.ts
  src/api/common/UserSettings.ts
  src/api/common/index.ts
  src/hooks/useSignUp.tsx
  src/pages/SignupPage.tsx
  src/pages/signup/SignUpForm.tsx
Labels: 🐣 Feat

#121 feat: ProfilePage API 연동 + 레이아웃
  src/api/fetchArticleById.ts
  src/api/getUserInfo.ts
  src/components/BottomNavigation.tsx
  src/components/HeaderText.tsx
  src/components/ScrollToTopButton.tsx
  src/constants/Article.ts
  src/hooks/useArticles.tsx
  src/hooks/useScrollToTop.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProfilePage/LikeArticles.tsx
  src/pages/ProfilePage/UserArticles.tsx
  src/type/User.ts
  src/utils/Router.tsx
Labels: 🐣 Feat

#128 design: 임시 파비콘 추가
  index.html
  public/favicon/android-icon-144x144.png
  public/favicon/android-icon-192x192.png
  public/favicon/android-icon-36x36.png
  public/favicon/android-icon-48x48.png
  public/favicon/android-icon-72x72.png
  public/favicon/android-icon-96x96.png
  public/favicon/apple-icon-114x114.png
  public/favicon/apple-icon-120x120.png
  public/favicon/apple-icon-144x144.png
  public/favicon/apple-icon-152x152.png
  public/favicon/apple-icon-180x180.png
  public/favicon/apple-icon-57x57.png
  public/favicon/apple-icon-60x60.png
  public/favicon/apple-icon-72x72.png
  public/favicon/apple-icon-76x76.png
  public/favicon/apple-icon-precomposed.png
  public/favicon/apple-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon-96x96.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/favicon/ms-icon-144x144.png
  public/favicon/ms-icon-150x150.png
  public/favicon/ms-icon-310x310.png
  public/favicon/ms-icon-70x70.png
Labels: 🎨 Design

#127 feat: 비밀번호 변경 페이지 구현
  src/App.tsx
  src/components/FormInput.tsx
  src/components/HeaderText.tsx
  src/hooks/useChangePassword.tsx
  src/pages/ChangePasswordPage.tsx
  src/pages/LoginPage.tsx
  src/pages/index.ts
  src/pages/temp.tsx
  src/utils/Router.tsx
Labels: 🐣 Feat

#130 refactor: 파일경로 수정
  src/components/Comment.tsx
  src/hooks/useArticleDetail.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/CommentInput.tsx
  src/pages/ArticleDetailPage/Comments.tsx
Labels: 🛠 Refactor

#136 feat: 메타 데이터 추가
  index.html
Labels: 🐣 Feat

#125 refactor: 네비게이션 프로필 버튼 수정 + 알림 페이지 오타 수정
  src/components/BottomNavigation.tsx
  src/pages/NotificationPage.tsx
Labels: 🛠 Refactor

#134 feat : 검색 페이지 구현
  src/api/search.ts
  src/components/SearchResultList.tsx
  src/components/SearchSkeleton.tsx
  src/components/SubButton.tsx
  src/components/UserListItem.tsx
  src/constants/Search.ts
  src/hooks/useDebounce.ts
  src/hooks/useFilteredSearchResult.tsx
  src/hooks/useRecentResult.tsx
  src/hooks/useSearch.tsx
  src/pages/SearchPage.tsx
  src/type/search.ts
Labels: 🐣 Feat

#138 fix: useArticleDetail 커스텀 훅 수정
  src/hooks/useArticleDetail.tsx
Labels: 🔨 Fix

#132 refactor: 프로필 페이지 로그아웃, 프로필 이미지 수정 기능 + 위로가기 버튼 오류 수정
  src/api/common/Auth.ts
  src/components/Article.tsx
  src/components/BottomNavigation.tsx
  src/constants/Tab.ts
  src/hooks/useFilteredArticles.tsx
  src/hooks/useScrollToTop.tsx
  src/pages/ArticlesPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfilePage.tsx
  src/stories/Tab.stories.tsx
Labels: 🛠 Refactor

#144 refactor : SubButton 컴포넌트 다크모드
  src/components/SubButton.tsx
Labels: 🛠 Refactor

#145 design: 모달 공통 컴포넌트 구현
  index.html
  src/components/Modals/Alert.tsx
  src/components/Modals/Confirm.tsx
  src/components/Modals/Portal.tsx
  src/hooks/useModal.tsx
Labels: 🐣 Feat, 🎨 Design

#147 feat: 프로필 수정 페이지 수정
  src/api/axiosClient.ts
  src/api/common/User.ts
  src/api/common/UserSettings.ts
  src/components/BottomNavigation.tsx
  src/components/MainButton.tsx
  src/hooks/useEditProfile.tsx
  src/pages/LandingPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfileEditPage/EditForm.tsx
Labels: 🐣 Feat

#155 feat: protect Router 추가
  src/pages/LandingPage.tsx
  src/pages/LoadingPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProtectedRouter.tsx
  src/pages/index.ts
  src/utils/Router.tsx
Labels: 🐣 Feat

#160 feat: 토스트 컴포넌트 호출 기능 구현
  src/App.tsx
  src/components/Toast.tsx
  src/context/ToastContext.tsx
  src/hooks/useToastContext.tsx
  tailwind.config.js
Labels: 🐣 Feat, 🎨 Design

#146 feat: 뜨거운/구독한 탭 기능 구현
  src/api/common/Post.ts
  src/components/Tab.tsx
  src/components/TabItem.tsx
  src/constants/Article.ts
  src/context/TabContext.tsx
  src/hooks/useFilteredArticles.tsx
  src/hooks/useScrollToTop.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/Articles.tsx
  src/pages/ArticlesPage/InfiniteScroll.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/stories/Tab.stories.tsx
Labels: 🐣 Feat

#153 feat: 글 상세 페이지 구현
  src/api/common/Comment.ts
  src/api/common/Like.ts
  src/api/common/Post.ts
  src/api/saveArticle.ts
  src/components/CloseButton.tsx
  src/components/Comment.tsx
  src/hooks/useArticle.tsx
  src/hooks/useArticleDetail.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/CommentInput.tsx
  src/pages/ArticleDetailPage/Comments.tsx
  src/pages/NewArticlePage.tsx
Labels: 🐣 Feat

#157 feat: 홈페이지 게시물 불러오기 구현
  src/constants/Home.ts
  src/pages/HomePage.tsx
Labels: 🐣 Feat

#161 feat: 프로필 페이지에서 사용자 이미지 볼 수 있도록 구현
  src/components/Avatar.tsx
  src/pages/ProfilePage.tsx
  src/stories/Avatar.stories.tsx
Labels: 🐣 Feat

#164 feat : 검색페이지 레이아웃 + 라우팅 처리
  src/api/common/Follow.ts
  src/api/common/Search.ts
  src/api/search.ts
  src/components/SearchResultList.tsx
  src/components/UserListItem.tsx
  src/hooks/useSearch.tsx
  src/pages/SearchPage.tsx
  src/type/search.ts
Labels: 🐣 Feat

#166 refactor: 유저 정보 캐시하는 방식 context 에서 react query로 수정, 인증에 관련된 쿼리들 한파일로 통합
  src/App.tsx
  src/api/common/Auth.ts
  src/components/BottomNavigation.tsx
  src/components/UserListItem.tsx
  src/context/AuthContext.tsx
  src/hooks/useAuthContext.tsx
  src/hooks/useAuthQuery.tsx
  src/hooks/useEditProfile.tsx
  src/hooks/useLogin.tsx
  src/hooks/useSignUp.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticlesPage.tsx
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/NewArticlePage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProtectedRouter.tsx
  src/pages/signup/SignUpForm.tsx
  src/utils/user.ts
Labels: 🛠 Refactor

#170 feat: 댓글 작성 시 알림 보내기 기능 추가
  src/api/common/Comment.ts
  src/hooks/useArticleDetail.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/CommentInput.tsx
  src/type/User.ts
Labels: 🐣 Feat

#172 feat: 토스트 메시지 일괄 적용
  public/favicon/manifest.json
  src/constants/Messages.ts
  src/hooks/useArticle.tsx
  src/hooks/useArticleDetail.tsx
  src/hooks/useAuthQuery.tsx
  src/hooks/useChangePassword.tsx
  src/hooks/useEditProfile.tsx
  src/pages/ProtectedRouter.tsx
Labels: 🐣 Feat

#174 design: 토스트 다크 모드 추가
  src/components/Toast.tsx
Labels: 🎨 Design

#176 design: 회원가입, 알림 페이지 레이아웃 수정, 다크모드일때 body 배경색 추가
  src/App.tsx
  src/index.css
  src/pages/LandingPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/SignupPage.tsx
Labels: 🎨 Design

#183 Fix : 하단 네비게이션바 버그 수정 + 추가사항 수정
  src/components/BottomNavigation.tsx
  src/components/CloseButton.tsx
  src/constants/Messages.ts
  src/pages/HomePage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/ProfileEditPage/EditForm.tsx
  src/pages/ProfilePage.tsx
  tailwind.config.js
Labels: 🐣 Feat, 🔨 Fix

#186 design: 랜딩, 로그인, 404 페이지 다크모드 추가
  src/pages/LandingPage.tsx
  src/pages/LoginPage.tsx
  src/pages/NotFoundPage.tsx
Labels: 🎨 Design

#184 design: 글 상세, 글 수정 페이지에서 다크모드시 오류
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/CommentInput.tsx
  src/pages/HomePage.tsx
  src/pages/NewArticlePage.tsx
Labels: 🎨 Design

#187 refactor: 프로필 페이지에서 사진 저장하도록 수정 + 톱니바퀴모양 버튼 추가(프로필 수정 페이지로 이동)
  src/pages/ProfilePage.tsx
Labels: 🛠 Refactor

#179 refactor: 게시글 페이지 중복 처리 + 탭 상수화, useTab훅으로 관리
  src/components/SearchResultList.tsx
  src/components/Tab.tsx
  src/constants/Tab.ts
  src/hooks/useFilteredSearchResult.tsx
  src/hooks/useTab.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/Articles.tsx
  src/pages/HomePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  src/stories/Tab.stories.tsx
  src/type/User.ts
Labels: 🛠 Refactor

#191 feat: 비밀번호 변경 페이지 모달 및 버튼 추가 + 다크모드 적용
  src/components/FormInput.tsx
  src/components/SubscribeInfo.tsx
  src/constants/Messages.ts
  src/pages/ChangePasswordPage.tsx
  src/pages/ProfileEditPage/EditForm.tsx
Labels: 🐣 Feat, 🎨 Design

#192 design: 다크모드 및 버그 수정
  src/components/Article.tsx
  src/components/Comment.tsx
  src/constants/Article.ts
  src/index.css
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/CommentInput.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/Articles.tsx
  src/pages/HomePage.tsx
  src/pages/NewArticlePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage.tsx
  tailwind.config.js
Labels: 🎨 Design

#193 feat: hot 게시글이 비어있을 때 화면
  src/pages/HomePage.tsx
  src/pages/HomePage/HotArticles.tsx
  src/pages/NotificationPage.tsx
Labels: 🐣 Feat

#199 feat: 좋아요 시 알림 보내기 기능 추가
  src/hooks/useLikeDeleteMutation.ts
  src/hooks/useLikeMutation.ts
  src/hooks/useNotification.tsx
  src/pages/ArticleDetailPage.tsx
Labels: 🐣 Feat

#200 feat: 글 작성 시 option 입력을 제목에서 빼기
  src/pages/NewArticlePage.tsx
Labels: 🐣 Feat

#203 fix: 게시글/프로필 탭 동작 버그 수정 + 구독자 탭 중복 _id버그 수정
  src/constants/Tab.ts
  src/hooks/useArticles.tsx
  src/hooks/useTab.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/Articles.tsx
  src/pages/HomePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProfilePage/UserArticles.tsx
  src/pages/SearchPage.tsx
  src/stories/Tab.stories.tsx
Labels: 🔨 Fix

#206 Feat : 알림 페이지 api 연동
  src/api/common/Auth.ts
  src/api/common/Chatting.ts
  src/api/common/Notification.ts
  src/components/Avatar.tsx
  src/components/Notice.tsx
  src/components/UserListItem.tsx
  src/hooks/useChattingQuery.tsx
  src/hooks/useNotificationQuery.tsx
  src/pages/NotificationPage.tsx
  src/pages/NotificationPage/helper.ts
  src/utils/user.ts
Labels: 🐣 Feat

#210 feat: 게시글 페이지 무한스크롤 구현
  src/constants/Tab.ts
  src/hooks/useArticles.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/RenderArticles.tsx
  src/pages/ArticlesPage/fetchArticles.ts
  src/pages/HomePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProfilePage/LikeArticles.tsx
  src/pages/ProfilePage/UserArticles.tsx
Labels: 🐣 Feat

#213 refactor: 좋아요, 댓글 작성 시 게시글 새로 받아오도록 수정 (구독한 탭은 추후 수정 예정)
  src/hooks/useArticleDetail.tsx
  src/hooks/useLikeMutation.ts
  src/pages/ArticleDetailPage/CommentInput.tsx
Labels: 🛠 Refactor

#207 refactor: 글 작성 페이지, 글 상세 페이지
  src/components/ArticleDetail.tsx
  src/components/Avatar.tsx
  src/components/Comment.tsx
  src/hooks/useArticle.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/Comments.tsx
  src/pages/ArticleEditPage.tsx
  src/pages/ArticleEditPage/ArticleEditForm.tsx
  src/pages/ArticleEditPage/ImagePreview.tsx
  src/pages/NewArticlePage.tsx
Labels: 🛠 Refactor

#221 refactor: 프로필 페이지 사진 변경 시 로딩 추가 + 사진 로딩 시 낙관적 업데이트 수행
  src/api/common/User.ts
  src/components/Skeleton/Circle.tsx
  src/components/Skeleton/UserSkeleton.tsx
  src/constants/Messages.ts
  src/constants/Tab.ts
  src/hooks/useImageMutation.ts
  src/hooks/useLikeMutation.ts
  src/pages/ArticleEditPage/ArticleEditForm.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProfilePage/LikeArticles.tsx
Labels: 🛠 Refactor

#220 fix: 좋아요 취소 누를 시 알림 가던 문제 해결
  src/pages/ArticleDetailPage.tsx
Labels: 🔨 Fix

#219 feat: PC화면 구현
  public/img/google-play.png
  public/img/notion-button.png
  src/App.tsx
  src/assets/icons/GithubIcon.tsx
  src/assets/icons/NotionIcon.tsx
  src/index.css
  src/pages/HomePage.tsx
  src/pages/MockUpPage.tsx
  tailwind.config.js
Labels: 🐣 Feat, 🎨 Design

#226 refactor: 게시글 페이지 탭 별로 컴포넌트 분리
  src/constants/Tab.ts
  src/hooks/useArticleDetail.tsx
  src/pages/ArticlesPage.tsx
  src/pages/ArticlesPage/RenderArticles.tsx
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
  src/pages/ArticlesPage/RenderHottestArticles.tsx
  src/pages/ArticlesPage/RenderNewestArticles.tsx
  src/pages/ArticlesPage/fetchArticles.ts
  src/pages/ArticlesPage/filterArticles.ts
  src/pages/ProfilePage.tsx
Labels: 🛠 Refactor

#227 refactor: 게시물 삭제 시 모달, 생성삭제 시 게시글 갱신
  src/hooks/useArticle.tsx
  src/hooks/useArticleDetail.tsx
  src/pages/ArticleDetailPage.tsx
Labels: 🛠 Refactor

#229 fix: 핫픽스 import 오류
  src/pages/ArticleDetailPage.tsx
Labels: 🔨 Fix

#230 fix: 네비게이션 바 알림 뱃지 디자인 수정
  src/components/BottomNavigation.tsx
Labels: 🎨 Design

#233 feat: 설정 버튼 드롭다운 메뉴 구현 및 사소한 수정
  src/components/BackButton.tsx
  src/pages/ProfilePage.tsx
Labels: 🐣 Feat, 🎨 Design

#237 feat: 다크모드 버튼 홈 화면에 추가
  src/components/DarkMode.tsx
  src/pages/HomePage.tsx
  tailwind.config.js
Labels: 🐣 Feat

#240 feat: 설정 드롭다운 비밀번호 변경 버튼 추가 및 사소한 수정
  src/constants/Messages.ts
  src/pages/ProfileEditPage/EditForm.tsx
  src/pages/ProfilePage.tsx
Labels: 🐣 Feat, 🔨 Fix

#242 fix: 게시글 작성 / 게시글 수정 페이지의 이미지 업데이트 로직 수정
  src/api/common/Post.ts
  src/components/TabItem.tsx
  src/constants/NewArticle.ts
  src/hooks/useArticle.tsx
  src/hooks/useEdit.tsx
  src/hooks/useLikeMutation.ts
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleEditPage.tsx
  src/pages/ArticleEditPage/ArticleEditForm.tsx
  src/pages/ArticleEditPage/ImagePreview.tsx
  src/pages/ArticlesPage/RenderArticles.tsx
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
  src/pages/NewArticlePage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ProfilePage/LikeArticles.tsx
  src/pages/ProfilePage/UserArticles.tsx
Labels: 🔨 Fix, 🛠 Refactor

#244 feat: 홈 배너 추가 및 레이아웃 수정 + 기타 수정
  public/img/banner-icon-1.png
  public/img/banner-icon-2.png
  public/img/google-play.png
  src/App.tsx
  src/components/Article.tsx
  src/components/Banner/HomeBanner.tsx
  src/components/BottomNavigation.tsx
  src/components/DarkMode.tsx
  src/index.css
  src/pages/HomePage.tsx
  src/pages/MockUpPage.tsx
Labels: 🐣 Feat, 🎨 Design

#248 refactor: 내가 응원하기누른 게시글 따봉아이콘 색깔 추가
  src/components/Article.tsx
  src/pages/ArticlesPage/RenderArticles.tsx
  src/pages/ArticlesPage/RenderHottestArticles.tsx
Labels: 🛠 Refactor

#245 Refactor : 홈페이지 스피너 + 뉴스 게시판 스피너 수정
  src/components/Article.tsx
  src/components/Skeleton/Box.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticlesPage/RenderArticles.tsx
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
  src/pages/ArticlesPage/RenderHottestArticles.tsx
  src/pages/ArticlesPage/RenderNewestArticles.tsx
  src/pages/HomePage.tsx
  src/pages/HomePage/HotArticles.tsx
Labels: 🛠 Refactor

#253 fix: import 구문 에러 수정
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
Labels: 🔨 Fix, 🔥 우선순위 높음

#251 design: notification page filter ui 수정
  src/pages/NotificationPage.tsx
Labels: 🎨 Design

#263 hotfix: 채널아이디 변경
  src/constants/Article.ts
Labels: 🔨 Fix, 🔥 우선순위 높음

#261 refactor: png 파일 webp로 변경
  public/img/404.png
  public/img/404.webp
  public/img/banner-icon-1.png
  public/img/banner-icon-1.webp
  public/img/banner-icon-2.png
  public/img/banner-icon-2.webp
  public/img/character.png
  public/img/character.webp
  public/img/notion-button.png
  public/img/notion-button.webp
  src/pages/HomePage.tsx
  src/pages/LandingPage.tsx
  src/pages/MockUpPage.tsx
  src/pages/NotFoundPage.tsx
Labels: 🛠 Refactor

#266 fix: 다크모드 사용자 컬러모드로 초기 설정
  src/components/DarkMode.tsx
Labels: 🔨 Fix

#278 fix: 로그아웃 시 캐시 삭제 + 커스텀 훅 쿼리키 수정 + 구독한 탭 스켈레톤 오류 수정
  src/hooks/useAuthQuery.tsx
  src/hooks/useFollowQuery.tsx
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
Labels: 🔨 Fix, 🔥 우선순위 높음

#280 refactor: 댓글 삭제 시 상세 페이지 반영 + 댓글 오류 메시지 삭제 + 제출 중 버튼 비활성화
  src/components/MainButton.tsx
  src/hooks/useArticleDetail.tsx
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticleDetailPage/CommentInput.tsx
  src/pages/ArticleDetailPage/Comments.tsx
  src/pages/NewArticlePage.tsx
Labels: 🛠 Refactor

#283 chore : 깃허브 액션 스크립트 수정 282
  .github/workflows/chromatic.yml
  .husky/pre-push
Labels: 🏅 Chore

#286 chore : 빌드 테스트 깃허브 액션 추가
  .github/workflows/build-test.yml
Labels: 🏅 Chore

#287 fix: 게시글 이미지 아이콘 오류 수정 + 구독한 탭 스켈레톤 및 무한 스크롤 수정
  src/constants/Article.ts
  src/pages/ArticlesPage/RenderArticles.tsx
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
  src/pages/ArticlesPage/fetchArticles.ts
Labels: 🔨 Fix, 🔥 우선순위 높음

#292 fix: 구독한 탭에서 네트워크 요청 전에 텍스트 나오는 현상 수정
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
Labels: 🔨 Fix, 🔥 우선순위 높음

#291 refactor: 뜨거운뉴스 좋아요+토스트 수정
  src/pages/ArticleDetailPage.tsx
  src/pages/ArticlesPage.tsx
  src/pages/HomePage/HotArticles.tsx
  src/pages/NotificationPage/NoticeList.tsx
Labels: 🛠 Refactor

#293 fix: 다크 모드 버그 수정
  src/App.tsx
  src/components/DarkModeButton.tsx
  src/context/DarkModeContext.tsx
  src/hooks/useThemeContext.tsx
  src/main.tsx
  src/pages/HomePage.tsx
Labels: 🔨 Fix, 🔥 우선순위 높음

#294 feat: 프로필 페이지 구독, 구독취소 버튼 구현
  src/constants/Messages.ts
  src/hooks/useFollowQuery.tsx
  src/pages/ProfilePage.tsx
  src/pages/SearchPage/UserListItem.tsx
Labels: 🐣 Feat

#295 hotFix/article detail 댓글 내리기, 이미지 alt
  src/pages/ArticleDetailPage.tsx
Labels: 🔨 Fix

#302 feat: 웹 폰트 렌더링 방식 변경
  src/index.css
Labels: 🐣 Feat

#304 fix: 구독한 탭 스켈레톤이 안보이고 로더만 보이는 이슈 수정
  src/pages/ArticlesPage/RenderFollowingArticles.tsx
Labels: 🔨 Fix, 🔥 우선순위 높음

#310 fix: 글 상세 페이지 공백 처리 방식 변경
  src/pages/ArticleDetailPage.tsx
Labels: 🔨 Fix
